FROM node:16.14.0

WORKDIR /anime-service

COPY package*.json .

RUN npm install

RUN groupadd -r vlad && useradd -g vlad vlad

RUN chown -R vlad:vlad /anime-service

USER vlad

RUN ["npm", "run", "start"]